"""empty message

Revision ID: 081f4fc034a6
Revises: 9c2d855be5e8
Create Date: 2022-09-14 14:11:17.736466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081f4fc034a6'
down_revision = '9c2d855be5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
