"""empty message

Revision ID: 1dcee0221f7c
Revises: c0edf98e80a4
Create Date: 2022-09-18 10:11:40.915991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcee0221f7c'
down_revision = 'c0edf98e80a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('cap', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cap')
    op.drop_column('users', 'cp')
    # ### end Alembic commands ###
