"""empty message

Revision ID: c0edf98e80a4
Revises: c78574f50591
Create Date: 2022-09-15 06:47:49.491408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0edf98e80a4'
down_revision = 'c78574f50591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('status', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('referrals', sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'date_created')
    op.drop_column('referrals', 'status')
    # ### end Alembic commands ###
